# Generated by Django 5.2.3 on 2025-06-19 23:58

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=accounts.models.user_directory_path
            ),
        ),
    ]
